### ISSUE TITLE
Settings don't persist after saving

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/element-index-defaults#1]
### Description
Just installed this locally to try out. Settings are returning to default after saving.

I have already customized most, if not all, of my index field displays individually.

### Steps to reproduce

1. Open plugin settings.
2. Change selected fields for Entries.
3. Save. 
4. See "Plugin settings saved" banner.
5. Settings are returned to default.

### Additional info

- Plugin version: 1.0.0
- Craft version: Craft Pro 3.0.5

**Comment by engram-design** [comment]
Fixed in [1.0.1](https://github.com/verbb/element-index-defaults/releases/tag/1.0.1)

**Comment by KatieMFritz** [comment]
That did the trick, thanks!
