### ISSUE TITLE
Twig Runtime Error when clicking settings

### ISSUE THREAD

**Issue by bartrylant** [verbb/element-index-defaults#3]
### Description
When clicking the plugin settings button, I get a twig error. I guess it refers to a field that I renamed after creating the field. (I renamed "bestand" to "documenten")

```
Twig Runtime Error – Twig_Error_Runtime
Key "Bestand" in object with ArrayAccess of class "verbb\elementindexdefaults\models\Settings" does not exist.
```

**Comment by engram-design** [comment]
I'm not seeing this happen when renaming a field, but this can happen if you remove or delete the field.  Fixed in [1.0.2](https://github.com/verbb/element-index-defaults/releases/tag/1.0.2)
