### ISSUE TITLE
Settings don't persist with Craft 3.1.8

### ISSUE THREAD

**Issue by jonleverrier** [verbb/element-index-defaults#4]
### Description

Similar to https://github.com/verbb/element-index-defaults/issues/1, the plugin settings don't seem to reflect in either assets, entries and categories.

### Steps to reproduce

1. Install the plugin
2. Go to plugin settings
3. Click on assets
4. Hide the `title` field and save
5. Go to an asset, and notice that the title column is still present

### Additional info

- Plugin version: 1.0.2
- Craft version: 3.1.8

**Comment by engram-design** [comment]
Might need some better clarification around what can and can't be disabled. For example, the Title field on most of these items can't be disabled (try and disable it via Assets).

I have just added this in https://github.com/verbb/element-index-defaults/releases/tag/1.0.3

Or, are you still seeing this with other fields? I can disable all the other columns, and it does show just the Title for assets for example.

**Comment by jonleverrier** [comment]
Hi @engram-design 

I tried disabling the title field through the plugin settings, because it was available to disable. I think this is what through me! If it can't be disabled or removed, then the title field in the plugin settings should be disabled like it is natively. Everything else works as expected.

**Comment by engram-design** [comment]
Yeah, though that might be the issue, so added that clarification in 1.0.3.
