### ISSUE TITLE
Plugin Settings don't show up

### ISSUE THREAD

**Issue by luke-nehemedia** [verbb/element-index-defaults#5]
### Description
I installed the plugin but I cannot find any settings. I checked for a "Settings" link on the list of installed plugins, on the settings page and on the tools page.

### Additional info
- Plugin version: 1.0.5
- Craft version: 3.4.30

**Comment by engram-design** [comment]
Fixed in [1.0.6](https://github.com/verbb/element-index-defaults/releases/tag/1.0.6)
